#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-parsedate
Version  : 1.3.2
Release  : 39
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/parsedate_1.3.2.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/parsedate_1.3.2.tar.gz
Summary  : Recognize and Parse Dates in Various Formats, Including All ISO
Group    : Development/Tools
License  : GPL-2.0
Requires: R-parsedate-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
format. Currently it includes the git date parser.  It can also
    recognize and parse all ISO 8601 formats.

%package lib
Summary: lib components for the R-parsedate package.
Group: Libraries

%description lib
lib components for the R-parsedate package.


%prep
%setup -q -n parsedate
pushd ..
cp -a parsedate buildavx2
popd
pushd ..
cp -a parsedate buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1733825273

%install
export SOURCE_DATE_EPOCH=1733825273
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/parsedate/DESCRIPTION
/usr/lib64/R/library/parsedate/INDEX
/usr/lib64/R/library/parsedate/Meta/Rd.rds
/usr/lib64/R/library/parsedate/Meta/features.rds
/usr/lib64/R/library/parsedate/Meta/hsearch.rds
/usr/lib64/R/library/parsedate/Meta/links.rds
/usr/lib64/R/library/parsedate/Meta/nsInfo.rds
/usr/lib64/R/library/parsedate/Meta/package.rds
/usr/lib64/R/library/parsedate/NAMESPACE
/usr/lib64/R/library/parsedate/NEWS.md
/usr/lib64/R/library/parsedate/R/parsedate
/usr/lib64/R/library/parsedate/R/parsedate.rdb
/usr/lib64/R/library/parsedate/R/parsedate.rdx
/usr/lib64/R/library/parsedate/help/AnIndex
/usr/lib64/R/library/parsedate/help/aliases.rds
/usr/lib64/R/library/parsedate/help/parsedate.rdb
/usr/lib64/R/library/parsedate/help/parsedate.rdx
/usr/lib64/R/library/parsedate/help/paths.rds
/usr/lib64/R/library/parsedate/html/00Index.html
/usr/lib64/R/library/parsedate/html/R.css
/usr/lib64/R/library/parsedate/tests/testthat.R
/usr/lib64/R/library/parsedate/tests/testthat/helper.R
/usr/lib64/R/library/parsedate/tests/testthat/test-corner-cases.R
/usr/lib64/R/library/parsedate/tests/testthat/test-git.r
/usr/lib64/R/library/parsedate/tests/testthat/test-iso8601.r
/usr/lib64/R/library/parsedate/tests/testthat/test-time-zones.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/parsedate/libs/parsedate.so
/V4/usr/lib64/R/library/parsedate/libs/parsedate.so
/usr/lib64/R/library/parsedate/libs/parsedate.so
